config/routes.rb
FoodsMonitor::Application.routes.draw do
  get "basic/search"
  post "basic/handle_barcode_search"

  resources :product_detail_entries

  resources :organizations

  resources :product_details

  devise_for :users

  resources :products
  
  resources :users do
    resources :product_details do
      post 'bulk_update', :on => :collection
    end
  end

  root :to =>  "product_details#index"

end

app/models/organization.rb
class Organization < ActiveRecord::Base
    has_many :product_detail_organizations
    has_many :product_details, :through => :product_detail_organizations
    
    # for geo coding
    geocoded_by :full_address
    after_validation :geocode
    
    def full_address
        return address
        # SUG: try to use multiple map service to pin point the accurate address and geo code.
    end
    
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.xml
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.xml
  def show
    @organization = Organization.find(params[:id])
    
    # demo place for 
    # temporary placing of Goolge Map
    @map = Cartographer::Gmap.new( 'map' )
    @map.zoom = :bound
    @icon = Cartographer::Gicon.new()
    @map.icons <<  @icon
    marker1 = Cartographer::Gmarker.new(:name=> "taj_mahal", :marker_type => "Building",
               :position => [27.173006,78.042086],
               :info_window_url => "/url_for_info_content", :icon => @icon)
    marker2 = Cartographer::Gmarker.new(:name=> "raj_bhawan", :marker_type => "Building",
               :position => [28.614309,77.201353],
               :info_window_url => "/url_for_info_content", :icon => @icon)
    
    @map.markers << marker1
    @map.markers << marker2
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.xml
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.xml
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to(@organization, :notice => 'Organization was successfully created.') }
        format.xml  { render :xml => @organization, :status => :created, :location => @organization }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @organization.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.xml
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to(@organization, :notice => 'Organization was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @organization.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.xml
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to(organizations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country_code %><br />
    <%= f.text_field :country_code %>
  </div>
  <div class="field">
    <%= f.label :city_code %><br />
    <%= f.text_field :city_code %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address_en %><br />
    <%= f.text_field :address_en %>
  </div>
  <div class="field">
    <%= f.label :office_tel %><br />
    <%= f.text_field :office_tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country code</th>
    <th>City code</th>
    <th>Address</th>
    <th>Address en</th>
    <th>Office tel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= organization.country_code %></td>
    <td><%= organization.city_code %></td>
    <td><%= organization.address %></td>
    <td><%= organization.address_en %></td>
    <td><%= organization.office_tel %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Country code:</b>
  <%= @organization.country_code %>
</p>

<p>
  <b>City code:</b>
  <%= @organization.city_code %>
</p>

<p>
  <b>Address:</b>
  <%= @organization.address %>
</p>

<p>
  <b>Address en:</b>
  <%= @organization.address_en %>
</p>

<p>
  <b>Office tel:</b>
  <%= @organization.office_tel %>
</p>

<p>
  <b>Latitude:</b>
  <%= @organization.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @organization.longitude %>
</p>

<p>
  <b>Geocode:</b>
  <%= Geocoder.coordinates(@organization.address) %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>



 <h2>for Rails 3+ you need to make use of 'raw'  </h2>
 <%= raw Cartographer::Header.new.to_s %>
 <%= raw @map.to_html %>