config/routes.rb
FoodsMonitor::Application.routes.draw do
  get "basic/search"
  post "basic/handle_barcode_search"

  resources :product_detail_entries

  resources :organizations

  resources :product_details

  devise_for :users

  resources :products
  
  resources :users do
    resources :product_details do
      post 'bulk_update', :on => :collection
    end
  end

  root :to =>  "product_details#index"

end

app/models/product_detail_entry.rb
class ProductDetailEntry < ActiveRecord::Base
  
  belongs_to :product_detail
end

app/controllers/product_detail_entries_controller.rb
class ProductDetailEntriesController < ApplicationController
  # GET /product_detail_entries
  # GET /product_detail_entries.xml
  def index
    @product_detail_entries = ProductDetailEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @product_detail_entries }
    end
  end

  # GET /product_detail_entries/1
  # GET /product_detail_entries/1.xml
  def show
    @product_detail_entry = ProductDetailEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product_detail_entry }
    end
  end

  # GET /product_detail_entries/new
  # GET /product_detail_entries/new.xml
  def new
    @product_detail_entry = ProductDetailEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product_detail_entry }
    end
  end

  # GET /product_detail_entries/1/edit
  def edit
    @product_detail_entry = ProductDetailEntry.find(params[:id])
  end

  # POST /product_detail_entries
  # POST /product_detail_entries.xml
  def create
    @product_detail_entry = ProductDetailEntry.new(params[:product_detail_entry])

    respond_to do |format|
      if @product_detail_entry.save
        format.html { redirect_to(@product_detail_entry, :notice => 'Product detail entry was successfully created.') }
        format.xml  { render :xml => @product_detail_entry, :status => :created, :location => @product_detail_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product_detail_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /product_detail_entries/1
  # PUT /product_detail_entries/1.xml
  def update
    @product_detail_entry = ProductDetailEntry.find(params[:id])

    respond_to do |format|
      if @product_detail_entry.update_attributes(params[:product_detail_entry])
        format.html { redirect_to(@product_detail_entry, :notice => 'Product detail entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product_detail_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /product_detail_entries/1
  # DELETE /product_detail_entries/1.xml
  def destroy
    @product_detail_entry = ProductDetailEntry.find(params[:id])
    @product_detail_entry.destroy

    respond_to do |format|
      format.html { redirect_to(product_detail_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/product_detail_entries_helper.rb
module ProductDetailEntriesHelper
end

app/views/product_detail_entries/_form.html.erb
<%= form_for(@product_detail_entry) do |f| %>
  <% if @product_detail_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_detail_entry.errors.count, "error") %> prohibited this product_detail_entry from being saved:</h2>

      <ul>
      <% @product_detail_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_detail_entries/edit.html.erb
<h1>Editing product_detail_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_detail_entry %> |
<%= link_to 'Back', product_detail_entries_path %>

app/views/product_detail_entries/index.html.erb
<h1>Listing product_detail_entries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_detail_entries.each do |product_detail_entry| %>
  <tr>
    <td><%= product_detail_entry.name %></td>
    <td><%= product_detail_entry.value %></td>
    <td><%= product_detail_entry.type %></td>
    <td><%= link_to 'Show', product_detail_entry %></td>
    <td><%= link_to 'Edit', edit_product_detail_entry_path(product_detail_entry) %></td>
    <td><%= link_to 'Destroy', product_detail_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product detail entry', new_product_detail_entry_path %>

app/views/product_detail_entries/new.html.erb
<h1>New product_detail_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', product_detail_entries_path %>

app/views/product_detail_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product_detail_entry.name %>
</p>

<p>
  <b>Value:</b>
  <%= @product_detail_entry.value %>
</p>

<p>
  <b>Type:</b>
  <%= @product_detail_entry.type %>
</p>


<%= link_to 'Edit', edit_product_detail_entry_path(@product_detail_entry) %> |
<%= link_to 'Back', product_detail_entries_path %>